services:
  frontend:
    build: ./frontend
    restart: unless-stopped
    container_name: fastsend-frontend
    ports:
      - "5180:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: fastsend-backend
    restart: unless-stopped
    ports:
      - "9003:9003"
    volumes:
      - ./data_bak:/usr/src/app/database/prod_data
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - AI_MODEL=${AI_MODEL:-llama-3.3-70b-versatile}

networks:
  default:
    external: true
    name: caddy
